# Generated by Django 3.0.5 on 2023-07-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etablissement', '0002_auto_20230717_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='id',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='Id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
