# Generated by Django 4.2.3 on 2023-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Lab', models.CharField(max_length=100, null=True, unique=True)),
                ('Type', models.CharField(max_length=100)),
                ('Localisation', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Abrv', models.CharField(max_length=50)),
            ],
        ),
    ]
