# Generated by Django 3.0.5 on 2023-07-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratoire', '0003_laboratoire_etablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoire',
            name='Etablissement',
        ),
    ]
