# Generated by Django 3.0.5 on 2023-07-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratoire', '0005_laboratoire_etablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoire',
            name='Type',
        ),
    ]
