# Generated by Django 4.2.3 on 2023-07-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=200, unique=True)),
                ('Genre', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('Prenom_v', models.CharField(max_length=200, null=True)),
                ('Nom_V', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
