name: Build and deploy Python app to Azure Web App - appswiam

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django
          pip install Django-filter
          pip install Django-auditlog
          pip install selenium
          pip install mysqlclient
      - name: Install required packages for headless browser
        run: sudo apt-get install -y xvfb

      - name: Run Tests
        run: |
          # Start Xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x16 &
          # Run the test script
          python test.py  # Replace this with your actual test command
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      
